### ISSUE TITLE
The blink example doesn't work with wifi kit 8  

### ISSUE THREAD

**Issue by illxi** [Heltec-Aaron-Lee/WiFi_Kit_series#1]
Blink:18: error: 'LED_BUILTIN' was not declared in this scope

   digitalWrite(LED_BUILTIN, LOW);   // Turn the LED on (Note that LOW is the voltage level

                ^

exit status 1
'LED_BUILTIN' was not declared in this scope

**Comment by fedy0** [comment]
Check the hardware variant you selected. Ensure it's heltec_wifi_kit or heltec_wifi_lora that you selected under board menu (if it's not there then update your SDK)
OR
Include this in your sketch
static const uint8_t LED_BUILTIN = 25
Then recompile

**Comment by Heltec-Aaron-Lee** [comment]
Very sorry, there don't have a LED for user in WIFI Kit 8...

We will fix it next version.
