### ISSUE TITLE
Esp8266 json doesn't work

### ISSUE THREAD

**Issue by decobeto** [Heltec-Aaron-Lee/WiFi_Kit_series#114]
I can't install documentation libraries because esp8266 json has problems

https://docs.heltec.cn/download/package_heltec_esp8266_index.json

![image](https://user-images.githubusercontent.com/32197501/70639194-e67d8500-1c18-11ea-8d03-c88b1f1dfc5b.png)

**Comment by SauloAislan** [comment]
Try this: http://arduino.esp8266.com/stable/package_esp8266com_index.json

**Comment by SauloAislan** [comment]
This is a problem on line 44 has garbage:

![2019-12-12 12 23 11 docs heltec cn 63458ac005bf](https://user-images.githubusercontent.com/15917116/70725303-e940ae80-1cda-11ea-91b4-c4890089de5d.png)

**Comment by SauloAislan** [comment]
See https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/releases

**Comment by decobeto** [comment]
I saw the problem, I tried to work around using the tutorial from this site https://robotzero.one/heltec-wifi-kit-8/, but my esp doesn't seem to work well with the libraries for esp8266

**Comment by SauloAislan** [comment]
See: https://docs.heltec.cn/#/en/user_manual/how_to_install_esp8266_Arduino?id=step1-download-arduino-esp8266-support

**Comment by SauloAislan** [comment]
What is the model of your board?

**Comment by SauloAislan** [comment]
Resolved https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/issues/110

**Comment by decobeto** [comment]
Esp8266 heltec wifi kit 8, I reinstalled the arduino IDE and now it's working
