### ISSUE TITLE
Timed out waiting for packet header

### ISSUE THREAD

**Issue by royheuer** [Heltec-Aaron-Lee/WiFi_Kit_series#16]
Good day

I am trying to connect to ESP32 LoRa device but get A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header.  This is on a Mac.

I have done the following:
- Installed the drivers
- Tried to press the PRG button when programming
- Tried to start the device when PRG button is pressed
- Tried to change the programming speed
- Have tried on 2 different devices.

Nothing works. Please help.

**Comment by royheuer** [comment]
I have also tried two different USB cables

**Comment by DeuxVis** [comment]
Can you please tell us how you fixed that @royheuer ? It might help other people.
