### ISSUE TITLE
How to stop batt LED flashing

### ISSUE THREAD

**Issue by Eddiiie** [Heltec-Aaron-Lee/WiFi_Kit_series#17]
Hello,

The battery LED always flashes.  I do not plan to use battery.  How do I stop the flashing and just leave it off?

**Comment by DeuxVis** [comment]
There is no software solution for now. You have to de-solder the led.

**Comment by aderusha** [comment]
If you power the device from the 3.3V pin the battery charger won't be enabled and will stop blinking.

**Comment by Eddiiie** [comment]
Thank you!
