### ISSUE TITLE
Can I set 433MHz frequency if I have a 470MHz board?

### ISSUE THREAD

**Issue by pbecchi** [Heltec-Aaron-Lee/WiFi_Kit_series#26]
Actually my new Heltec ESP32 LoRa board with 470MHz stamp on the envelope cannot talk with a AiThinker Ra 02 433Mz module.
Is this due to the different frequencies?  Can I change the frequncy to 433?

Thanks

**Comment by Heltec-Aaron-Lee** [comment]
Of course you can.

**Comment by pbecchi** [comment]
Sorry but then what os the difference from a 470 and a 433 model?
