### ISSUE TITLE
Unable To Install Arduino Tools

### ISSUE THREAD

**Issue by davidbitton** [Heltec-Aaron-Lee/WiFi_Kit_series#3]
Do to the fact that the packages.json file points to arduino.esp8266.com, it fails. There is more detail here: https://github.com/esp8266/Arduino/issues/3198

**Comment by Heltec-Aaron-Lee** [comment]
https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series#instructions

here is the install guides, you can check you internet and try again.
