### ISSUE TITLE
display.drawXbm compile error OLED_LoRa_Receiver / OLED_LoRa_Sender

### ISSUE THREAD

**Issue by JBSchueler** [Heltec-Aaron-Lee/WiFi_Kit_series#59]
When I compile the examples `OLED_LoRa_Receiver` / `OLED_LoRa_Sender` I get an error at line 45 / 48.
I am using Arduino 1.8.5 by the way.

```
OLED_LoRa_Receiver:45: error: invalid conversion from 'char*' to 'const uint8_t* {aka const unsigned char*}' [-fpermissive]

   display.drawXbm(0,5,logo_width,logo_height,logo_bits);

                                                       ^
```

Both files have the same line of code at that point
```c
  display.drawXbm(0,5,logo_width,logo_height,logo_bits);
```

If I cast cast logo_bits to uint8_t* it does compile...
```c
  display.drawXbm(0,5,logo_width,logo_height,(uint8_t*)logo_bits);
```
Is this a bug in the code or am I doing something wrong???

**Comment by JBSchueler** [comment]
Thank you @solotaker to fix this in commit f971dc8c06b24b261bda4c56536126032cd5b4f0

**Comment by JBSchueler** [comment]
Ticket can be closed

**Comment by Cerunnos75** [comment]
I use the heltec 0.0.5 board driver and the heltec 1.1.0 libary, but get exactly the same error.
What am I doing wrong?

**Comment by JBSchueler** [comment]
check if the `logo_bits` is being cast to `(uint8_t*)`

**Comment by Cerunnos75** [comment]
Thanks a lot. That was the missing point .....
