### ISSUE TITLE
Can you post the esp32 Lora v2 schematic

### ISSUE THREAD

**Issue by kampto** [Heltec-Aaron-Lee/WiFi_Kit_series#63]
Can you post the esp32 Lora v2 schematic? GitHub still only has V1 schematic.   Its difficult to see how the Pin 13 battery voltage divider works since there no documentation. And Pins 34 and 35 seem to operate differently than V1.  V1 boards I had some Analog iinputs on 34 and 35 and they dont work anymore on V2.

**Comment by moloned** [comment]
Any progress on posting the schematics

**Comment by kampto** [comment]
V2 schematic is posted now. Appears pin 13 is tied to a battery V-divider and enables Vext by using Pin 21. But confused about why Vext is tied to the RF chip and what DIO1 and DIO2 (formerly GPIO's on V1) do.

**Comment by rodri16** [comment]
https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/blob/master/SchematicDiagram/WiFi_LoRa_32(V2)

**Comment by rodri16** [comment]
So with Pin 21 you control Vext and detect battery level BUT Pin 21 is SDA for I2C, so If I use I2C I cannot use Pin 21 for controlling Vext and detect battery??

**Comment by Heltec-Aaron-Lee** [comment]
@rodri16 yes. but I2C pin can be MUX to any GPIO
