### ISSUE TITLE
i2c sensor not working with wifi lora esp32 (mpu6050)

### ISSUE THREAD

**Issue by cdoern** [Heltec-Aaron-Lee/WiFi_Kit_series#68]
please explain how t wire up and code an mpu6050 with this board. the i2c does not seem to be working since the OLED is using the SDA pin. there must be another way to access i2c, please help!

**Comment by itofficeeu** [comment]
Take a look here. Maybe this can help you:
https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/issues/62#issuecomment-449690785
