### ISSUE TITLE
remote control button

### ISSUE THREAD

**Issue by lbernstone** [Heltec-Aaron-Lee/WiFi_Kit_series#7]
Do you know of any remote control buttons that will work with the SX1278 in this module?

**Comment by DeuxVis** [comment]
A bit of websearch should provide some possibilities. As long as the button can use the same LORA frequency as your SX1278 module - 433Mhz I suppose - you're good.

Some pointers here : https://www.thethingsnetwork.org/forum/t/amazon-dash-button-equivalent/1371/12
